language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "node"

sudo: false

env:
    - HAPI_VERSION=""

matrix:
  include:
  - node_js: "4"
    env: HAPI_VERSION="@13"
  - node_js: "4"
    env: HAPI_VERSION="@14"
  - node_js: "4"
    env: HAPI_VERSION="@15"
  - node_js: "6"
    env: HAPI_VERSION="@13"
  - node_js: "6"
    env: HAPI_VERSION="@14"
  - node_js: "6"
    env: HAPI_VERSION="@15"

install:
    - npm install
    - npm install hapi$HAPI_VERSION
