language: node_js

node_js:
  - "4"
  - "6"
  - "7"
  - "node"

sudo: false

env:
    - HAPI_VERSION="@13"
    - HAPI_VERSION="@14"
    - HAPI_VERSION="@15"
    - HAPI_VERSION=""

matrix:
  exclude:
  - node_js: "node"
    env: HAPI_VERSION="@13"
  - node_js: "node"
    env: HAPI_VERSION="@14"
  - node_js: "node"
    env: HAPI_VERSION="@15"

install:
    - npm install
    - npm install hapi$HAPI_VERSION
